name: CI

on:
  pull_request:

jobs:
  docs:
    name: Documentation
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: python -m pip install -r docs/requirements.txt

      - name: Intall draw.io dependencies
        run: |
          wget -O drawio.deb https://github.com/jgraph/drawio-desktop/releases/download/v20.6.2/drawio-amd64-20.6.2.deb
          sudo apt install xvfb ./drawio.deb

      - name: Build documentation
        run: python -m sphinx -b html -E docs docs/_build

      - name: Archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: |
            docs/_build
          if-no-files-found: error

  # TODO: upload docs to github pages

  validate-network:
    name: Validate network
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install library
        run: python -m pip install git+https://github.com/c4deszes/bike-line-protocol.git#subdirectory=python-lib

      - name: Validate network
        run: python validate.py
